# BASIC SETTINGS
#title: Dr. Jeremy S. Johnson
#email: jeremyjo@msu.edu
#github_username: Pine-Forest-Health
#twitter_username: treelinescience

#header_pages:
#  - index.md
#  - CV.md
#  - Lab-Documents.md
  
# BUILD SETTINGS
#markdown: kramdown
#theme: jekyll-theme-tactile

# Site settings
title: MSU Forest Genetics
author:
  name: Dr. Jeremy S. Johnson
  email: jeremyjo@msu.edu
description: "Info on lab people, projects, and oportunities"

# Build settings
remote_theme: jekyll/minima
