# BASIC SETTINGS
#title: Dr. Jeremy S. Johnson
#email: jeremyjo@msu.edu
#github_username: Pine-Forest-Health
#twitter_username: treelinescience

#header_pages:
#  - index.md
#  - CV.md
#  - Lab-Documents.md
  
# BUILD SETTINGS
#markdown: kramdown
#theme: jekyll-theme-tactile

# Site settings
title: Great New Blog Title
author:
  name: Evan Will
  email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
