# Site settings
title: Lab Website
author:
  name: Dr. Jeremy S. Johnson
  email: jeremyjo@msu.edu
description: "Info on lab people, projects, and oportunities"

# Build settings
remote_theme: jekyll/minima
