# Site settings
title: MSU Forest Genetics Lab
author:
  name: Dr. Jeremy S. Johnson
  email: jeremyjo@msu.edu
description: "Info on lab people, projects, and oportunities"

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
